{
    "name": "Discount Coupons",
    "version": "1.1.12",
    "summary": "Manage discount coupons and apply them to sales",
    "description": "This module allows you to create, manage, and apply discount coupons in sales and POS.",
    "author": "CodeTrade India Pvt.Ltd.",
    "website": "https://www.codetrade.io",
    "depends": ["sale", "base", "point_of_sale","loyalty","pos_loyalty","replace_date_to_datetime","sale_loyalty","pos_discount_config"],
    "data": [
        "security/ir.model.access.csv",
        "data/pos_discount_category.xml",
        "views/loyalty_card_views.xml",
        "views/product_template.xml",
        "views/loyalty_program_views.xml",
        "views/sale_order_views.xml",
        "wizards/loyalty_genarate_wizard.xml",
        "wizards/excel_report_views.xml",
        "wizards/loyalty_assign_store_wizard.xml",
        "wizards/stock_move_wizard.xml",
        "wizards/multiple_loyalty_assign_store_wizard_views.xml",
        "wizards/generate_coupon_wizard.xml",
        "wizards/security_code_import.xml",
        "views/sale_report_coupon_inherit.xml",
        "views/delivery_report_coupon_inherit.xml",
        "views/coupon_adjustment_views.xml",
    ],
    "assets": {
        "point_of_sale._assets_pos": [
            "discount_coupans/static/src/js/validate_order.js",
            "discount_coupans/static/src/js/coupon_code_validation.js",
            "discount_coupans/static/src/js/multi_coupon_redemption.js",
            "discount_coupans/static/src/js/coupon_orderline_display.js",
            "discount_coupans/static/src/js/pos_lot_number.js",
            "discount_coupans/static/src/js/coupon_range.js",
            "discount_coupans/static/src/xml/coupon_range.xml",
            "discount_coupans/static/src/xml/product_display_template.xml",
        ],
        "web.assets_backend": [
            "discount_coupans/static/src/js/stock_move_quantity.js",
            "discount_coupans/static/src/js/security_code_import_progress.js",
            "discount_coupans/static/src/xml/security_code_import_progress.xml",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
